import unittest

from MathProtEnergyProc.tests.TestGenerateRandomdatasInDiapasons import TestGenerateRandomdatasInDiapasons
from MathProtEnergyProc.tests.TestHStackMatrixRepeat import TestHStackMatrixRepeat
from MathProtEnergyProc.tests.TestHStackMatrixRepeatTwo import TestHStackMatrixRepeatTwo
from MathProtEnergyProc.tests.TestHVStackMatrixRepeat import TestHVStackMatrixRepeat
from MathProtEnergyProc.tests.TestComputingExperimentBegDatasAugmentation import TestComputingExperimentBegDatasAugmentation
from MathProtEnergyProc.tests.TestComputingExperimentBegDatasAugmentationQ import TestComputingExperimentBegDatasAugmentationQ
from MathProtEnergyProc.tests.TestConcatRepeatIndexes import TestConcatRepeatIndexes
from MathProtEnergyProc.tests.TestIndexedNamesFromIndexes import TestIndexedNamesFromIndexes
from MathProtEnergyProc.tests.TestAllIndexedNamesFromIndexes import TestAllIndexedNamesFromIndexes
from MathProtEnergyProc.tests.TestIndexedNames import TestIndexedNames
from MathProtEnergyProc.tests.TestAllIndexedNames import TestAllIndexedNames
from MathProtEnergyProc.tests.TestNonEq import TestNonEqSystem
from MathProtEnergyProc.tests.TestNonEqQ import TestNonEqSystemQ
from MathProtEnergyProc.tests.TestNonEqBase import TestNonEqSystemBase
from MathProtEnergyProc.tests.TestNonEqQBase import TestNonEqSystemQBase
from MathProtEnergyProc.tests.TestNonEqDyn import TestNonEqSystemDyn
from MathProtEnergyProc.tests.TestNonEqDynQ import TestNonEqSystemDynQ
from MathProtEnergyProc.tests.TestNonEqComExp import TestNonEqSystemComExp
from MathProtEnergyProc.tests.TestNonEqComExpQ import TestNonEqSystemComExpQ
from MathProtEnergyProc.tests.TestNonEqComExpModel import TestNonEqSystemComExpModel
from MathProtEnergyProc.tests.TestNonEqComExpModelQ import TestNonEqSystemComExpModelQ
from MathProtEnergyProc.tests.TestNonEqComExpModelLearning import TestNonEqSystemComExpModelLearning
from MathProtEnergyProc.tests.TestNonEqComExpModelLearningQ import TestNonEqSystemComExpModelLearningQ
from MathProtEnergyProc.tests.TestPosLinearFilter import TestPosLinearFilter
from MathProtEnergyProc.tests.TestExpFilter import TestExpFilter
from MathProtEnergyProc.tests.TestKineticMatrixFromPosSubMatrix import TestKineticMatrixFromPosSubMatrix
from MathProtEnergyProc.tests.TestKineticMatrixFromSymAsym import TestKineticMatrixFromSymAsym
from MathProtEnergyProc.tests.TestReluFilter import TestReluFilter
from MathProtEnergyProc.tests.TestSymRevMatrix import TestSymRevMatrix
from MathProtEnergyProc.tests.TestSymAndAsymRevMatrix import TestSymAndAsymRevMatrix
from MathProtEnergyProc.tests.TestKineticMatrixFromFacStreamEkvAff import TestKineticMatrixFromFacStreamEkvAff
from MathProtEnergyProc.tests.TestKineticMarix import TestKineticMarix
from MathProtEnergyProc.tests.TestKineticMarixQ import TestKineticMarixQ
from MathProtEnergyProc.tests.TestBetaProcess import TestBetaProcess
from MathProtEnergyProc.tests.TestBetaMatrix import TestBetaMatrix

#Запустить тестирование
if __name__ == "__main__":
    unittest.main()
