import unittest

from MathProtEnergyProc.tests.TestGenerateRandomdatasInDiapasons import TestGenerateRandomdatasInDiapasons
from MathProtEnergyProc.tests.TestHStackMatrixRepeat import TestHStackMatrixRepeat
from MathProtEnergyProc.tests.TestHStackMatrixRepeatTwo import TestHStackMatrixRepeatTwo
from MathProtEnergyProc.tests.TestHVStackMatrixRepeat import TestHVStackMatrixRepeat
from MathProtEnergyProc.tests.TestComputingExperimentBegDatasAugmentation import TestComputingExperimentBegDatasAugmentation
from MathProtEnergyProc.tests.TestComputingExperimentBegDatasAugmentationQ import TestComputingExperimentBegDatasAugmentationQ
from MathProtEnergyProc.tests.TestConcatRepeatIndexes import TestConcatRepeatIndexes
from MathProtEnergyProc.tests.TestIndexedNamesFromIndexes import TestIndexedNamesFromIndexes
from MathProtEnergyProc.tests.TestAllIndexedNamesFromIndexes import TestAllIndexedNamesFromIndexes
from MathProtEnergyProc.tests.TestIndexedNames import TestIndexedNames
from MathProtEnergyProc.tests.TestAllIndexedNames import TestAllIndexedNames
from MathProtEnergyProc.tests.TestNonEq import TestNonEqSystem
from MathProtEnergyProc.tests.TestNonEqQ import TestNonEqSystemQ
from MathProtEnergyProc.tests.TestNonEqDyn import TestNonEqSystemDyn
from MathProtEnergyProc.tests.TestNonEqDynQ import TestNonEqSystemDynQ
from MathProtEnergyProc.tests.TestNonEqComExp import TestNonEqSystemComExp
from MathProtEnergyProc.tests.TestNonEqComExpQ import TestNonEqSystemComExpQ
from MathProtEnergyProc.tests.TestNonEqComExpModel import TestNonEqSystemComExpModel
from MathProtEnergyProc.tests.TestNonEqComExpModelQ import TestNonEqSystemComExpModelQ
from MathProtEnergyProc.tests.TestNonEqComExpModelLearning import TestNonEqSystemComExpModelLearning
from MathProtEnergyProc.tests.TestNonEqComExpModelLearningQ import TestNonEqSystemComExpModelLearningQ

#Запустить тестирование
if __name__ == "__main__":
    unittest.main()
