import numpy as np

from MathProtEnergyProc.IndexedNames import AllIndexedNames

import unittest


# Модульные тесты
class TestAllIndexedNames(unittest.TestCase):
    def setUp(self):
        # Выполнить настройку тестов (если необходимо)
        pass

    def tearDown(self):
        # Выполнить завершающие действия (если необходимо)
        pass

    # Модульные тесты
    def testAllIndexedNames1(self):
        # Исходные данные
        rangeIndexes1 = (0, 2, 1)
        rangeIndexes2 = (1, 7, 2)
        rangeIndexes3 = (2, 14, 3)
        listIndexesDiapasons = [rangeIndexes1,
                                rangeIndexes2,
                                rangeIndexes3]
        beginName1 = "v"  # Начало имени
        endName1 = ""  # Конец имени
        sepName1 = "_"  # Раздлитель имени
        selectIndexes1 = [0, 2]
        beginName2 = "w"  # Начало имени
        endName2 = ""  # Конец имени
        sepName2 = "_"  # Раздлитель имени
        selectIndexes2 = [1, 0]
        partsNames = [(beginName1, endName1, sepName1, selectIndexes1),
                      (beginName2, endName2, sepName2, selectIndexes2)]

        # Индексированные имена
        IndexedNamesEt1 = ["v0_2",
                           "v0_5",
                           "v0_8",
                           "v0_11",
                           "v0_2",
                           "v0_5",
                           "v0_8",
                           "v0_11",
                           "v0_2",
                           "v0_5",
                           "v0_8",
                           "v0_11",
                           "v1_2",
                           "v1_5",
                           "v1_8",
                           "v1_11",
                           "v1_2",
                           "v1_5",
                           "v1_8",
                           "v1_11",
                           "v1_2",
                           "v1_5",
                           "v1_8",
                           "v1_11"]
        IndexedNamesEt2 = ["w1_0",
                           "w1_0",
                           "w1_0",
                           "w1_0",
                           "w3_0",
                           "w3_0",
                           "w3_0",
                           "w3_0",
                           "w5_0",
                           "w5_0",
                           "w5_0",
                           "w5_0",
                           "w1_1",
                           "w1_1",
                           "w1_1",
                           "w1_1",
                           "w3_1",
                           "w3_1",
                           "w3_1",
                           "w3_1",
                           "w5_1",
                           "w5_1",
                           "w5_1",
                           "w5_1"]

        # Генерируем индексированные имена
        [IndexedNames1,
         IndexedNames2] = AllIndexedNames(listIndexesDiapasons,  # Индексы
                                          partsNames  # Части имен
                                          )

        # Проверяем значения
        self.assertTrue(np.all(IndexedNames1 == IndexedNamesEt1))
        self.assertTrue(np.all(IndexedNames2 == IndexedNamesEt2))

    def testAllIndexedNames2(self):
        # Исходные данные
        rangeIndexes1 = (0, 5, 2)
        rangeIndexes2 = (1, 8, 3)
        rangeIndexes3 = (1, 7, 1)
        rangeIndexes4 = (3, 24, 5)
        listIndexesDiapasons = [rangeIndexes1,
                                rangeIndexes2,
                                rangeIndexes3,
                                rangeIndexes4]
        beginName1 = "b"  # Начало имени
        endName1 = "e"  # Конец имени
        sepName1 = "_"  # Раздлитель имени
        selectIndexes1 = [1, 3]
        beginName2 = "bv"  # Начало имени
        endName2 = "ev"  # Конец имени
        sepName2 = "@"  # Раздлитель имени
        selectIndexes2 = [2]
        beginName3 = "bw"  # Начало имени
        endName3 = "ew"  # Конец имени
        sepName3 = "&"  # Раздлитель имени
        selectIndexes3 = [0, 2, 3]
        partsNames = [(beginName1, endName1, sepName1, selectIndexes1),
                      (beginName2, endName2, sepName2, selectIndexes2),
                      (beginName3, endName3, sepName3, selectIndexes3)]

        # Индексированные имена
        IndexedNamesEt1 = ["b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b1_3e",
                           "b1_8e",
                           "b1_13e",
                           "b1_18e",
                           "b1_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b4_3e",
                           "b4_8e",
                           "b4_13e",
                           "b4_18e",
                           "b4_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e",
                           "b7_3e",
                           "b7_8e",
                           "b7_13e",
                           "b7_18e",
                           "b7_23e"]
        IndexedNamesEt2 = ["bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv1ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv2ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv3ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv4ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv5ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev",
                           "bv6ev"]
        IndexedNamesEt3 = ["bw0&1&3ew",
                           "bw0&1&8ew",
                           "bw0&1&13ew",
                           "bw0&1&18ew",
                           "bw0&1&23ew",
                           "bw0&2&3ew",
                           "bw0&2&8ew",
                           "bw0&2&13ew",
                           "bw0&2&18ew",
                           "bw0&2&23ew",
                           "bw0&3&3ew",
                           "bw0&3&8ew",
                           "bw0&3&13ew",
                           "bw0&3&18ew",
                           "bw0&3&23ew",
                           "bw0&4&3ew",
                           "bw0&4&8ew",
                           "bw0&4&13ew",
                           "bw0&4&18ew",
                           "bw0&4&23ew",
                           "bw0&5&3ew",
                           "bw0&5&8ew",
                           "bw0&5&13ew",
                           "bw0&5&18ew",
                           "bw0&5&23ew",
                           "bw0&6&3ew",
                           "bw0&6&8ew",
                           "bw0&6&13ew",
                           "bw0&6&18ew",
                           "bw0&6&23ew",
                           "bw0&1&3ew",
                           "bw0&1&8ew",
                           "bw0&1&13ew",
                           "bw0&1&18ew",
                           "bw0&1&23ew",
                           "bw0&2&3ew",
                           "bw0&2&8ew",
                           "bw0&2&13ew",
                           "bw0&2&18ew",
                           "bw0&2&23ew",
                           "bw0&3&3ew",
                           "bw0&3&8ew",
                           "bw0&3&13ew",
                           "bw0&3&18ew",
                           "bw0&3&23ew",
                           "bw0&4&3ew",
                           "bw0&4&8ew",
                           "bw0&4&13ew",
                           "bw0&4&18ew",
                           "bw0&4&23ew",
                           "bw0&5&3ew",
                           "bw0&5&8ew",
                           "bw0&5&13ew",
                           "bw0&5&18ew",
                           "bw0&5&23ew",
                           "bw0&6&3ew",
                           "bw0&6&8ew",
                           "bw0&6&13ew",
                           "bw0&6&18ew",
                           "bw0&6&23ew",
                           "bw0&1&3ew",
                           "bw0&1&8ew",
                           "bw0&1&13ew",
                           "bw0&1&18ew",
                           "bw0&1&23ew",
                           "bw0&2&3ew",
                           "bw0&2&8ew",
                           "bw0&2&13ew",
                           "bw0&2&18ew",
                           "bw0&2&23ew",
                           "bw0&3&3ew",
                           "bw0&3&8ew",
                           "bw0&3&13ew",
                           "bw0&3&18ew",
                           "bw0&3&23ew",
                           "bw0&4&3ew",
                           "bw0&4&8ew",
                           "bw0&4&13ew",
                           "bw0&4&18ew",
                           "bw0&4&23ew",
                           "bw0&5&3ew",
                           "bw0&5&8ew",
                           "bw0&5&13ew",
                           "bw0&5&18ew",
                           "bw0&5&23ew",
                           "bw0&6&3ew",
                           "bw0&6&8ew",
                           "bw0&6&13ew",
                           "bw0&6&18ew",
                           "bw0&6&23ew",
                           "bw2&1&3ew",
                           "bw2&1&8ew",
                           "bw2&1&13ew",
                           "bw2&1&18ew",
                           "bw2&1&23ew",
                           "bw2&2&3ew",
                           "bw2&2&8ew",
                           "bw2&2&13ew",
                           "bw2&2&18ew",
                           "bw2&2&23ew",
                           "bw2&3&3ew",
                           "bw2&3&8ew",
                           "bw2&3&13ew",
                           "bw2&3&18ew",
                           "bw2&3&23ew",
                           "bw2&4&3ew",
                           "bw2&4&8ew",
                           "bw2&4&13ew",
                           "bw2&4&18ew",
                           "bw2&4&23ew",
                           "bw2&5&3ew",
                           "bw2&5&8ew",
                           "bw2&5&13ew",
                           "bw2&5&18ew",
                           "bw2&5&23ew",
                           "bw2&6&3ew",
                           "bw2&6&8ew",
                           "bw2&6&13ew",
                           "bw2&6&18ew",
                           "bw2&6&23ew",
                           "bw2&1&3ew",
                           "bw2&1&8ew",
                           "bw2&1&13ew",
                           "bw2&1&18ew",
                           "bw2&1&23ew",
                           "bw2&2&3ew",
                           "bw2&2&8ew",
                           "bw2&2&13ew",
                           "bw2&2&18ew",
                           "bw2&2&23ew",
                           "bw2&3&3ew",
                           "bw2&3&8ew",
                           "bw2&3&13ew",
                           "bw2&3&18ew",
                           "bw2&3&23ew",
                           "bw2&4&3ew",
                           "bw2&4&8ew",
                           "bw2&4&13ew",
                           "bw2&4&18ew",
                           "bw2&4&23ew",
                           "bw2&5&3ew",
                           "bw2&5&8ew",
                           "bw2&5&13ew",
                           "bw2&5&18ew",
                           "bw2&5&23ew",
                           "bw2&6&3ew",
                           "bw2&6&8ew",
                           "bw2&6&13ew",
                           "bw2&6&18ew",
                           "bw2&6&23ew",
                           "bw2&1&3ew",
                           "bw2&1&8ew",
                           "bw2&1&13ew",
                           "bw2&1&18ew",
                           "bw2&1&23ew",
                           "bw2&2&3ew",
                           "bw2&2&8ew",
                           "bw2&2&13ew",
                           "bw2&2&18ew",
                           "bw2&2&23ew",
                           "bw2&3&3ew",
                           "bw2&3&8ew",
                           "bw2&3&13ew",
                           "bw2&3&18ew",
                           "bw2&3&23ew",
                           "bw2&4&3ew",
                           "bw2&4&8ew",
                           "bw2&4&13ew",
                           "bw2&4&18ew",
                           "bw2&4&23ew",
                           "bw2&5&3ew",
                           "bw2&5&8ew",
                           "bw2&5&13ew",
                           "bw2&5&18ew",
                           "bw2&5&23ew",
                           "bw2&6&3ew",
                           "bw2&6&8ew",
                           "bw2&6&13ew",
                           "bw2&6&18ew",
                           "bw2&6&23ew",
                           "bw4&1&3ew",
                           "bw4&1&8ew",
                           "bw4&1&13ew",
                           "bw4&1&18ew",
                           "bw4&1&23ew",
                           "bw4&2&3ew",
                           "bw4&2&8ew",
                           "bw4&2&13ew",
                           "bw4&2&18ew",
                           "bw4&2&23ew",
                           "bw4&3&3ew",
                           "bw4&3&8ew",
                           "bw4&3&13ew",
                           "bw4&3&18ew",
                           "bw4&3&23ew",
                           "bw4&4&3ew",
                           "bw4&4&8ew",
                           "bw4&4&13ew",
                           "bw4&4&18ew",
                           "bw4&4&23ew",
                           "bw4&5&3ew",
                           "bw4&5&8ew",
                           "bw4&5&13ew",
                           "bw4&5&18ew",
                           "bw4&5&23ew",
                           "bw4&6&3ew",
                           "bw4&6&8ew",
                           "bw4&6&13ew",
                           "bw4&6&18ew",
                           "bw4&6&23ew",
                           "bw4&1&3ew",
                           "bw4&1&8ew",
                           "bw4&1&13ew",
                           "bw4&1&18ew",
                           "bw4&1&23ew",
                           "bw4&2&3ew",
                           "bw4&2&8ew",
                           "bw4&2&13ew",
                           "bw4&2&18ew",
                           "bw4&2&23ew",
                           "bw4&3&3ew",
                           "bw4&3&8ew",
                           "bw4&3&13ew",
                           "bw4&3&18ew",
                           "bw4&3&23ew",
                           "bw4&4&3ew",
                           "bw4&4&8ew",
                           "bw4&4&13ew",
                           "bw4&4&18ew",
                           "bw4&4&23ew",
                           "bw4&5&3ew",
                           "bw4&5&8ew",
                           "bw4&5&13ew",
                           "bw4&5&18ew",
                           "bw4&5&23ew",
                           "bw4&6&3ew",
                           "bw4&6&8ew",
                           "bw4&6&13ew",
                           "bw4&6&18ew",
                           "bw4&6&23ew",
                           "bw4&1&3ew",
                           "bw4&1&8ew",
                           "bw4&1&13ew",
                           "bw4&1&18ew",
                           "bw4&1&23ew",
                           "bw4&2&3ew",
                           "bw4&2&8ew",
                           "bw4&2&13ew",
                           "bw4&2&18ew",
                           "bw4&2&23ew",
                           "bw4&3&3ew",
                           "bw4&3&8ew",
                           "bw4&3&13ew",
                           "bw4&3&18ew",
                           "bw4&3&23ew",
                           "bw4&4&3ew",
                           "bw4&4&8ew",
                           "bw4&4&13ew",
                           "bw4&4&18ew",
                           "bw4&4&23ew",
                           "bw4&5&3ew",
                           "bw4&5&8ew",
                           "bw4&5&13ew",
                           "bw4&5&18ew",
                           "bw4&5&23ew",
                           "bw4&6&3ew",
                           "bw4&6&8ew",
                           "bw4&6&13ew",
                           "bw4&6&18ew",
                           "bw4&6&23ew"]

        # Генерируем индексированные имена
        [IndexedNames1,
         IndexedNames2,
         IndexedNames3] = AllIndexedNames(listIndexesDiapasons,  # Индексы
                                          partsNames  # Части имен
                                          )

        # Проверяем значения
        self.assertTrue(np.all(IndexedNames1 == IndexedNamesEt1))
        self.assertTrue(np.all(IndexedNames2 == IndexedNamesEt2))
        self.assertTrue(np.all(IndexedNames3 == IndexedNamesEt3))

    def testAllIndexedNames3(self):
        # Исходные данные
        rangeIndexes1 = (2, 9, 2)
        rangeIndexes2 = (1, 10, 4)
        listIndexesDiapasons = [rangeIndexes1,
                                rangeIndexes2]
        beginName = "beg"  # Начало имени
        endName = "end"  # Конец имени
        sepName = "@"  # Раздлитель имени
        selectIndexes = [1, 0]
        partsNames = [(beginName, endName, sepName, selectIndexes)]

        # Индексированные имена
        IndexedNamesEt = ["beg1@2end",
                          "beg5@2end",
                          "beg9@2end",
                          "beg1@4end",
                          "beg5@4end",
                          "beg9@4end",
                          "beg1@6end",
                          "beg5@6end",
                          "beg9@6end",
                          "beg1@8end",
                          "beg5@8end",
                          "beg9@8end"]

        # Генерируем индексированные имена
        IndexedNames = AllIndexedNames(listIndexesDiapasons,  # Индексы
                                       partsNames  # Части имен
                                       )

        # Проверяем значения
        self.assertTrue(np.all(IndexedNames[0] == IndexedNamesEt))


# Запустить тестирование
if __name__ == "__main__":
    unittest.main()
